version: '3.6'

volumes:
  exec_data:

services:
  redis:
    image: redis:latest
    command: --port 5040
    ports:
      - "5040:5040"
    networks:
      - default
  qsharp-service:
    image: kuhnmx/qsharp-service:latest
    command: sh /app/startup.sh
    ports:
      - "5022:5022"
    environment:
      - REDIS_URL=redis://redis:5040
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    networks:
      - default

  rq-worker:
    image: kuhnmx/qsharp-service:latest
    command: rq worker --url redis://redis:5040 qsharp-service_execute
    environment:
      - REDIS_URL=redis://redis:5040
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    depends_on:
      - redis
    deploy:
      replicas: 4
    networks:
      - default

networks:
  default:
    driver: bridge
